spring.application.name=ecom-application

# Enable the web-based visual interface to inspect data via browser
spring.h2.console.enabled=true

# Configure a temporary, in-memory database named 'test'
spring.datasource.url=jdbc:h2:mem:test
#this comment enables query logging in on console
spring.jpa.show-sql = true
# this creates a table based on the entity class and the create comment for every restart you have drop the table and create a new table.
# There if you use update there it will upadte the existing table and modify if any new fileds added
spring.jpa.hibernate.ddl-auto = create
